In [1]:
import numpy as np

# Normal array

In [2]:
arr1=np.array([1,2,3,4])  
arr1                            #creating a normal array with numpy

array([1, 2, 3, 4])

In [3]:
tuple1=(5,10,15,20)
arr2=np.array(tuple1)
arr2                            #converting a tuple into array

array([ 5, 10, 15, 20])

# Numpy.zeros()         array with elments as zero

In [4]:
arr3=np.zeros(5)
arr3                            #creating 1D array with elements as zero

array([0., 0., 0., 0., 0.])

In [7]:
arr4=np.zeros((3,2))
arr4                            #creating 2D array with elements as zero con tains extra bracket

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
arr5=np.zeros((2,3,2))
arr5                            #creating a 3D array with all elements as zero 

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

# Numpy.ones()                 Array with elements as one

In [10]:
arr6=np.ones(5)                #creating 1D array with all calues as one
arr6 

array([1., 1., 1., 1., 1.])

In [12]:
arr7=np.ones((2,3))                #creating 2D array with all calues as one
arr7

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
arr8=np.ones((2,3,3))                #creating 3D array with all calues as one
arr8

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

# Numpy.arange()                     array with a specific range

In [15]:
arr9=np.arange(10)              #creating 1D array with specific range
arr9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr10=np.arange(10,20)              #creating 1D array with specific range
arr10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
arr11=np.arange(10,50,5)         #array in a specific range incrementing with 5
arr11

array([10, 15, 20, 25, 30, 35, 40, 45])

In [25]:
arr12=np.arange(10,50,5.0)         #array in a specific range incrementing with 5 and datatype is float
arr12

array([10., 15., 20., 25., 30., 35., 40., 45.])

In [27]:
arr13=np.linspace(1,10)                #same difference bw adjacent values
arr13

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [29]:
arr14=np.linspace(1,10,5)                #same difference bw adjacent values and only 5 values are needed
arr14

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [31]:
arr15=np.eye(4)     #creating 2D array with 4 rows and columns with diagonal elements as 1
arr15

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
arr16=np.eye(3,4)     #creating 2D array with different rows and columns with diagonal elements as 1
arr16

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [34]:
arr17=np.eye(3,4,k=1)     #K is the index of starting 1, positive 1=row -1=column
arr17

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
np.full(5,10)      #array with 5 elements and all elements are 10

array([10, 10, 10, 10, 10])

In [39]:
np.full((3,4),5)   #2D array with all aelements are 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [41]:
np.full((3,3,4),5)         #3D array with all aelements are 5

array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])

In [43]:
np.random.randint(0,10,5)   #1D array with random numbers from 1-10 and size is 5

array([6, 4, 6, 0, 8])

In [45]:
np.random.randint(0,10,(2,3))   #2D array with random numbers from 1-10 and size row=2 column=3 =6 

array([[9, 7, 6],
       [5, 1, 0]])

In [46]:
np.random.randint(0,10,(2,3,4))  #3D array

array([[[6, 0, 7, 6],
        [7, 7, 6, 9],
        [7, 2, 4, 4]],

       [[6, 9, 4, 5],
        [1, 1, 5, 6],
        [1, 4, 5, 8]]])

In [48]:
np.random.randint(0,10,(2,3,3,4))  #4D array

array([[[[7, 9, 4, 0],
         [6, 7, 0, 0],
         [7, 8, 9, 6]],

        [[9, 3, 7, 8],
         [7, 2, 9, 1],
         [0, 1, 6, 7]],

        [[2, 2, 5, 9],
         [9, 8, 7, 7],
         [3, 5, 6, 5]]],


       [[[4, 4, 1, 6],
         [9, 9, 5, 6],
         [8, 0, 3, 5]],

        [[5, 2, 4, 1],
         [0, 4, 9, 3],
         [5, 4, 9, 1]],

        [[0, 2, 1, 2],
         [5, 0, 8, 5],
         [8, 3, 0, 4]]]])

In [49]:
np.random.random(5)     # 1D array with random float values

array([0.87794759, 0.56303306, 0.11074439, 0.90892658, 0.33252659])

In [57]:
np.random.random((3,4))  # 2D array with random float values

array([[0.86046084, 0.1828326 , 0.81569324, 0.61986393],
       [0.96257287, 0.41921203, 0.036986  , 0.77784883],
       [0.36888244, 0.12628633, 0.17774756, 0.20324036]])