# 1D to 2D array


In [1]:
import numpy as np


In [3]:
arr1=np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [4]:
newarr1=arr1.reshape(2,3)
newarr1           #1D to 2D array 2X3

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
newarr1.shape 

(2, 3)

# 1D to 3D array

In [7]:
arr2=np.array([1,2,3,4,5,6,7,8])
arr2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
newarr2=arr2.reshape(2,2,2)
newarr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

# 2D to 2D

In [10]:
arr3=np.array([
    [1,2],
    [3,4],
    [5,6],
    [7,8]
])
arr3

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [12]:
arr3.shape

(4, 2)

In [13]:
arr3.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# 2D to 3D

In [14]:
arr4=np.array([
    [1,2],
    [3,4],
    [5,6],
    [7,8]
])
arr4

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [15]:
arr4.shape

(4, 2)

In [18]:
arr4.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

#  3D to 2D

In [20]:
arr5=np.array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])
arr5

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [21]:
arr5.shape

(2, 2, 2)

In [24]:
arr5.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

#  Multi D to 1D

In [25]:
arr6=np.array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])
arr6

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [29]:
arr6.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8])