In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

## Find datatype of an array

In [3]:
arr1.dtype

dtype('int32')

In [4]:
arr2=np.array([1.1,2.1,3.1,4.1,5.1,6.1])
arr2

array([1.1, 2.1, 3.1, 4.1, 5.1, 6.1])

In [5]:
arr2.dtype

dtype('float64')

In [6]:
arr3=np.array(["a","b","c"])
arr3

array(['a', 'b', 'c'], dtype='<U1')

## create array with specified datatype

In [7]:
arr4=np.array([1,2,3,4,5,6],np.int8)
arr4

array([1, 2, 3, 4, 5, 6], dtype=int8)

In [8]:
arr4.dtype

dtype('int8')

In [9]:
arr5=np.array([1,2,3,4,5,6],np.float16)
arr5

array([1., 2., 3., 4., 5., 6.], dtype=float16)

## convert datatypes

In [11]:
arr6=np.array([1,2,3,4,5,6],np.int8)
arr6

array([1, 2, 3, 4, 5, 6], dtype=int8)

In [12]:
arr6.astype(np.float16)

array([1., 2., 3., 4., 5., 6.], dtype=float16)

In [13]:
arr7=np.array([1,2,3,4,5,6],np.int8)
arr7


array([1, 2, 3, 4, 5, 6], dtype=int8)