In [1]:
import numpy as np

In [3]:
list=[1,2,3,4,5]

In [4]:
arr=np.array(list)  #creating a nd array 

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
print(arr.ndim)  #ndim - print the dimension of the array

1


In [18]:
arr.size

5

In [19]:
arr.shape

(5,)

In [11]:
print(list*2)  #multiply the list

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [9]:
print(arr*2) #multiply the entire elements by 2

[ 2  4  6  8 10]


In [12]:
type(arr) # type of the array returns n- dimensional array (ndarray)

numpy.ndarray

In [15]:
arr2=np.array([5,10,15,20,25]) #creating np array directly

In [17]:
arr2

array([ 5, 10, 15, 20, 25])